### PR TITLE
Eosgalaxybp1

### PR DESCRIPTION
**Pull request by zyq20130111**
EOS Galaxy BP candidate info added

### CODE REVIEW

**Comment by makoshan** [comment]
请修改图片文件命名与 branding 一致

```
"branding":{
      "logo": "logo-eosgalaxy.png",
     "cover": "cover-eosgalaxy.png"
    },
```

**Comment by zyq20130111** [comment]
modify eosgalaxybp1.json

**Comment by zyq20130111** [comment]
修改introudce

**Comment by zyq20130111** [comment]
"branding":{
      "logo": "logo-eosgalaxybp1.png",
      "cover": "cover-eosgalaxybp1.png"
    }

**Pull request merged**
