### PR TITLE
HKEOS - Hong Kong based Block Producer

### PR DESCRIPTION
**Pull request by Hgcam**
- json file
- logo
- cover

### CODE REVIEW

**Comment by makoshan** [comment]
你好，请移除 `bp/cover-hkeos.png` 该文件，中文介绍需要逗号隔开，branding 需要对于文件名，请参考一下修改，thanks.
```
{
  "title": "HKEOS",
  "tagline": {
    "en": "Hong Kong based EOS block producer candidate and the first DApps incubator.",
    "zh": "我们是一个以香港为基地的EOS区块生产者候选人和首个去中心化应用程式（DApp）孵化器。"
  },
  "introduce": {
    "en": "HKEOS is composed of experienced and talented professionals: 
          - Joseph Nejman is a proven entrepreneur and business builder, Harvard Alum and previoulsy worked at TomorrowVentures.
          - Sungjae Chung is an incoming Systems Engineering major at the University of Pennsylvania, he leaded the Ghostbusters testnet and is very active in the EOS dev community.
          - Hugo Campanella is a polyglot senior UX/UI designer and Front-End developer who leads HKEOS’ project execution and web-based products.
          - Devin Perera has been responsible for a number of successful businesses and initiatives, both in the traditional and digital ecosystems. He is now supporting the EOS community as a whole.
          ",
     "zh": "
          - JosephJoseph是一位经证实的企业家和业务建造者。
          - Sungjae是一位在香港读书十年的韩国学生。他是美国宾夕法尼亚大学（University of Pennsylvania）主修系统工程的来访交换生
          - Hugo是负责领导香港EOS项目执行的多元UX/UI设计师.
          - Devin曾经负责许多传统和数字生态系统中的成功企业。 
          "
  },
  "account_name": "HKEOS",
  "public_key": "",
  "org": {
    "name": "HKEOS",
    "website": "https://www.hkeos.com/",
    "email": "hugo@hkeos.com",
    "branding":{
      "logo": "logo-hkeos.png",
      "cover": "cover-hkeos.png"
    },
    "location": "Hong Kong",
    "social_network": {
      "steemit": "https://steemit.com/@hkeos",
      "twitter": "https://twitter.com/eos_hk",
      "github": "https://github.com/HKEOS",
      "telegram": "https://t.me/EOS_IO_Hong_KongP"
    }
  },
  "nodes": [
    {
      "location": {
        "id": "",
        "name": ""
      },
      "is_producer": false,
      "p2p_endpoint": "",
      "api_endpoint": "",
      "ssl_endpoint": ""
    }
  ]
}
```

**Comment by Hgcam** [comment]
@makoshan Updated the .jason file for Chinese translation and deleted the bp/cover-hkeos.png file.

**Comment by makoshan** [comment]
branding 的文件名也需要对应
```
 "branding":{
      "logo": "logo-hkeos.png",
      "cover": "cover-hkeos.png"
    }
```

**Comment by Hgcam** [comment]
@makoshan Corrected files names.

**Pull request merged**
