### PR TITLE
commit EOStark  file

### PR DESCRIPTION
**Pull request by yuantaowork**
commit EOStark  file

### CODE REVIEW

**Comment by yuantaowork** [comment]
resubmit EOStark.json with public_key

**Comment by yuantaowork** [comment]
resubmit EOStark.json

**Comment by yuantaowork** [comment]
resubmit EOStark

**Comment by yuantaowork** [comment]
resubmit EOStark

**Comment by yuantaowork** [comment]
resubmit EOStark

**Comment by yuantaowork** [comment]
update account_name

**Comment by makoshan** [comment]
请添加 BP 中文介绍

**Pull request closed without merging**
